// src/styles/icons.ts
import React from 'react';
import {
  Phone,
  Mail,
  MapPin,
  Github,
  Linkedin,
  Code2,
  Twitter,
  PenSquare,
  Globe,
  ChefHat,
  SquareStack,
  Dribbble,
  Hash,
  User,
  Star,
  Briefcase,
  GraduationCap,
  Settings,
  Key,
  Award,
  Target,
  GitBranch,
  CheckCircle2,
  Edit,
  Palette,
  Printer,
  LayoutTemplate,
  Move,
  Trash2,
  PlusCircle,
  Users,
  Tag,
  Trophy,
  ZoomIn,
  ZoomOut,
  Save,
  UploadCloud,
  RefreshCw,
  BookOpen,
  CloudUpload,
  LogOut
} from 'lucide-react';

const icons = new Map([
  ['mobile', <Phone key="phone" />],
  ['email', <Mail key="mail" />],
  ['location', <MapPin key="mappin" />],
  ['github', <Github key="github" />],
  ['linkedin', <Linkedin key="linkedin" />],
  ['hackerrank', <Code2 key="code2" />],
  ['hackerearth', <Code2 key="code2" />],
  ['twitter', <Twitter key="twitter" />],
  ['leetcode', <Code2 key="code2" />],
  ['devto', <BookOpen key="bookopen" />],
  ['medium', <PenSquare key="pensquare" />],
  ['wordpress', <Globe key="globe" />],
  ['codechef', <ChefHat key="chefhat" />],
  ['codeforces', <Code2 key="code2" />],
  ['behance', <Dribbble key="dribbble" />],
  ['dribbble', <Dribbble key="dribbble" />],
  ['hashnode', <Hash key="hash" />],
  ['squarespace', <SquareStack key="squarestack" />],

  ['identity', <User key="user" />],
  ['expert', <Star key="star" />],
  ['work', <Briefcase key="briefcase" />],
  ['education', <GraduationCap key="graduationcap" />],
  ['tool', <Settings key="settings" />],
  ['key', <Key key="key" />],
  ['certificate', <Award key="award" />],
  ['career', <Target key="target" />],
  ['branch', <GitBranch key="gitbranch" />],
  ['skill', <CheckCircle2 key="checkcircle" />],
  ['edit', <Edit key="edit" />],
  ['color', <Palette key="palette" />],
  ['print', <Printer key="printer" />],
  ['template', <LayoutTemplate key="layouttemplate" />],

  ['drag', <Move key="move" style={{ color: '#000000', stroke: '#000000' }} />],
  ['delete', <Trash2 key="trash" style={{ color: '#000000', stroke: '#000000' }} />],
  ['add', <PlusCircle key="pluscircle" />],
  ['social', <Users key="users" />],
  ['label', <Tag key="tag" />],
  ['awards', <Trophy key="trophy" />],
  ['zoomin', <ZoomIn key="zoomin" />],
  ['zoomout', <ZoomOut key="zoomout" />],
  ['save', <Save key="save" />],
  ['upload', <CloudUpload key="cloudupload" />],
  ['reset', <RefreshCw key="refresh" />],
  ['logout', <LogOut key="logout" />],
  ['globe', <Globe key="globe" />],
  ['language', <Globe key="language" />],
]);

export function getIcon(iconName: string) {
  return icons.get(iconName?.toLowerCase());
}